AWSTemplateFormatVersion: 2010-09-09
Description: Create admin group and user
Parameters:
  GroupName:
    Type: String
    Description: Administrator Group
    Default: Administrator

  UserName:
    Type: String
    Description: Admin username

  UserPassword:
    Type: String
    Description: User password
    Default: Passw0rd!

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${UserName}
      LoginProfile:
        Password: !Sub ${UserPassword}
        PasswordResetRequired: true

  Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${GroupName}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  IAMUserToGroupAdditionAllMember:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Group
      Users:
        - !Ref User

Outputs:
  UserPassword:
    Description: User password
    Value: !Sub ${UserPassword}
    Export:
      Name: !Sub ${AWS::StackName}-UserPassword
